[platform_archives.rustup-init.macos_aarch64]
url = "https://static.rust-lang.org/rustup/dist/x86_64-apple-darwin/rustup-init"
sha256 = "f547d77c32d50d82b8228899b936bf2b3c72ce0a70fb3b364e7fba8891eba781"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"

# more binaries https://forge.rust-lang.org/infra/other-installation-methods.html

[platform_archives.rustup-init.macos_x86_64]
url = "https://static.rust-lang.org/rustup/dist/x86_64-apple-darwin/rustup-init"
sha256 = "f547d77c32d50d82b8228899b936bf2b3c72ce0a70fb3b364e7fba8891eba781"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"

[env]
paths = ["{{spaces.store}}/cargo/bin", "{{spaces.store}}/rustup/bin"]
vars = { RUSTUP_HOME = "{{spaces.store}}/rustup", CARGO_HOME = "{{spaces.store}}/cargo" }
script =  """
FILE=/etc/resolv.conf
if [ -f "{{spaces.store}}/cargo/bin/cargo" ]; then
    echo "Rustup already installed"
else 
    rustup-init --default-host=x86_64-apple-darwin --default-toolchain=$RUSTUP_TOOLCHAIN --profile=default --no-modify-path -y
fi
"""

# download the RUSTUP binary
# Set RUSTUP_HOME to point to ~/.spaces/rustup
# Set RUSTUP_TOOLCHAIN to the toolchain desired for the workspace

# export RUSTUP_HOME=/Users/tgil/.spaces/store/rustup
# export CARGO_HOME=/Users/tgil/.spaces/store/cargo
# export RUSTUP_TOOLCHAIN=1.80
# export PATH=$PWD/sysroot/bin:$CARGO_HOME/bin:/usr/bin:/bin

# rustup-init --default-host=x86_64-apple-darwin --default-toolchain=$RUSTUP_TOOLCHAIN --profile=default --no-modify-path -y


[vscode.settings]
"rust-analyzer.cargo.buildScripts.invocationStrategy" = "once"
"rust-analyzer.cargo.buildScripts.invocationLocation" = "root"
"rust-analyzer.cargo.buildScripts.overrideCommand" = [
    "cargo",
    "check",
    "--quiet",
    "--message-format=json",
    "--all-targets",
    "--keep-going",
]
"rust-analyzer.cargo.targetDir" = "target-rust-analyzer"
"rust-analyzer.check.noDefaultFeatures" = true
"rust-analyzer.cargo.noDefaultFeatures" = true
"rust-analyzer.showUnlinkedFileNotification" = false
"rust-analyzer.imports.granularity.enforce" = true
"rust-analyzer.imports.granularity.group" = "module"
"rust-analyzer.cargo.buildScripts.enable" = true
"rust-analyzer.procMacro.attributes.enable" = false
